<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;


    class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [
                'role_id' => '1',
                'username' => 'adminNew',
                'body_id' => '1',
                'first_name' => 'AdminF',
                'last_name' => 'AdminL',
                'email' => 'admin@gmail.com',
                'gender' => 'M',
                'birth_date' => '2016-01-27 00:00:00',
                'mobile' => '1234567890',
                'password' => bcrypt('123456'),
                'address' => 'maharashtra Pune',
                'alternate_number' => '',
                'avatar' => 'default-user.jpg',
                'parent_id' => '0',
                'roll_number' => '0',
                'emp_type' => 'full_type',
                'division_id' => NULL,
                'is_active' => 1,
                'remember_token' => 'jznsnrBykw4NpyabN14uRVGFFXLsjqt3c87ZuwBSzoEehA87RTiZDKRLfX3F',
                'confirmation_code' => str_random(30),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'role_id' => '2',
                'username' => 'teacher1',
                'body_id' => '1',
                'first_name' => 'teacher1',
                'last_name' => 'teacher1',
                'email' => 'teacher1@gmail.com',
                'gender' => 'M',
                'birth_date' => '2016-01-27 00:00:00',
                'mobile' => '1234567890',
                'password' => bcrypt('123456'),
                'address' => 'maharashtra Pune',
                'alternate_number' => '',
                'avatar' => 'default-user.jpg',
                'parent_id' => '0',
                'roll_number' => '0',
                'emp_type' => 'full_type',
                'division_id' => NULL,
                'is_active' => 1,
                'remember_token' => 'jznsnrBykw4NpyabN14uRVGFFXLsjqt3c87ZuwBSzoEehA87RTiZDKRLfX3F',
                'confirmation_code' => str_random(30),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'role_id' => '2',
                'username' => 'teacher2',
                'body_id' => '1',
                'first_name' => 'teacher2',
                'last_name' => 'teacher2',
                'email' => 'teacher2@gmail.com',
                'gender' => 'M',
                'birth_date' => '2016-01-27 00:00:00',
                'mobile' => '1234567890',
                'password' => bcrypt('123456'),
                'address' => 'maharashtra Pune',
                'alternate_number' => '',
                'avatar' => 'default-user.jpg',
                'parent_id' => '0',
                'roll_number' => '0',
                'emp_type' => 'full_type',
                'division_id' => NULL,
                'is_active' => 1,
                'remember_token' => 'jznsnrBykw4NpyabN14uRVGFFXLsjqt3c87ZuwBSzoEehA87RTiZDKRLfX3F',
                'confirmation_code' => str_random(30),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
            'role_id' => '2',
            'username' => 'teacher3',
            'body_id' => '1',
            'first_name' => 'teacher3',
            'last_name' => 'teacher3',
            'email' => 'teacher3@gmail.com',
            'gender' => 'M',
            'birth_date' => '2016-01-27 00:00:00',
            'mobile' => '1234567890',
            'password' => bcrypt('123456'),
            'address' => 'maharashtra Pune',
            'alternate_number' => '',
            'avatar' => 'default-user.jpg',
            'parent_id' => '0',
            'roll_number' => '0',
            'emp_type' => 'full_type',
            'division_id' => NULL,
            'is_active' => 1,
            'remember_token' => 'jznsnrBykw4NpyabN14uRVGFFXLsjqt3c87ZuwBSzoEehA87RTiZDKRLfX3F',
            'confirmation_code' => str_random(30),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now()
            ],
            [
                'role_id' => '3',
                'username' => 'student1',
                'body_id' => '1',
                'first_name' => 'student1',
                'last_name' => 'student1',
                'email' => 'student1@gmail.com',
                'gender' => 'M',
                'birth_date' => '2016-01-27 00:00:00',
                'mobile' => '1234567890',
                'password' => bcrypt('123456'),
                'address' => 'maharashtra Pune',
                'alternate_number' => '',
                'avatar' => 'default-user.jpg',
                'parent_id' => '20',
                'roll_number' => '0',
                'emp_type' => 'full_type',
                'division_id' => 1,
                'is_active' => 1,
                'remember_token' => 'jznsnrBykw4NpyabN14uRVGFFXLsjqt3c87ZuwBSzoEehA87RTiZDKRLfX3F',
                'confirmation_code' => str_random(30),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'role_id' => '3',
                'username' => 'student2',
                'body_id' => '1',
                'first_name' => 'student2',
                'last_name' => 'student2',
                'email' => 'student2@gmail.com',
                'gender' => 'M',
                'birth_date' => '2016-01-27 00:00:00',
                'mobile' => '1234567890',
                'password' => bcrypt('123456'),
                'address' => 'maharashtra Pune',
                'alternate_number' => '',
                'avatar' => 'default-user.jpg',
                'parent_id' => '20',
                'roll_number' => '0',
                'emp_type' => 'full_type',
                'division_id' => 1,
                'is_active' => 1,
                'remember_token' => 'jznsnrBykw4NpyabN14uRVGFFXLsjqt3c87ZuwBSzoEehA87RTiZDKRLfX3F',
                'confirmation_code' => str_random(30),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'role_id' => '3',
                'username' => 'student3',
                'body_id' => '1',
                'first_name' => 'student3',
                'last_name' => 'student3',
                'email' => 'student3@gmail.com',
                'gender' => 'M',
                'birth_date' => '2016-01-27 00:00:00',
                'mobile' => '1234567890',
                'password' => bcrypt('123456'),
                'address' => 'maharashtra Pune',
                'alternate_number' => '',
                'avatar' => 'default-user.jpg',
                'parent_id' => '20',
                'roll_number' => '0',
                'emp_type' => 'full_type',
                'division_id' => 1,
                'is_active' => 1,
                'remember_token' => 'jznsnrBykw4NpyabN14uRVGFFXLsjqt3c87ZuwBSzoEehA87RTiZDKRLfX3F',
                'confirmation_code' => str_random(30),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'role_id' => '3',
                'username' => 'student4',
                'body_id' => '1',
                'first_name' => 'student4',
                'last_name' => 'student4',
                'email' => 'student4@gmail.com',
                'gender' => 'M',
                'birth_date' => '2016-01-27 00:00:00',
                'mobile' => '1234567890',
                'password' => bcrypt('123456'),
                'address' => 'maharashtra Pune',
                'alternate_number' => '',
                'avatar' => 'default-user.jpg',
                'parent_id' => '20',
                'roll_number' => '0',
                'emp_type' => 'full_type',
                'division_id' => 1,
                'is_active' => 1,
                'remember_token' => 'jznsnrBykw4NpyabN14uRVGFFXLsjqt3c87ZuwBSzoEehA87RTiZDKRLfX3F',
                'confirmation_code' => str_random(30),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'role_id' => '3',
                'username' => 'student5',
                'body_id' => '1',
                'first_name' => 'student5',
                'last_name' => 'student5',
                'email' => 'student5@gmail.com',
                'gender' => 'M',
                'birth_date' => '2016-01-27 00:00:00',
                'mobile' => '1234567890',
                'password' => bcrypt('123456'),
                'address' => 'maharashtra Pune',
                'alternate_number' => '',
                'avatar' => 'default-user.jpg',
                'parent_id' => '20',
                'roll_number' => '0',
                'emp_type' => 'full_type',
                'division_id' => 1,
                'is_active' => 1,
                'remember_token' => 'jznsnrBykw4NpyabN14uRVGFFXLsjqt3c87ZuwBSzoEehA87RTiZDKRLfX3F',
                'confirmation_code' => str_random(30),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'role_id' => '3',
                'username' => 'student6',
                'body_id' => '1',
                'first_name' => 'student6',
                'last_name' => 'student6',
                'email' => 'student6@gmail.com',
                'gender' => 'M',
                'birth_date' => '2016-01-27 00:00:00',
                'mobile' => '1234567890',
                'password' => bcrypt('123456'),
                'address' => 'maharashtra Pune',
                'alternate_number' => '',
                'avatar' => 'default-user.jpg',
                'parent_id' => '20',
                'roll_number' => '0',
                'emp_type' => 'full_type',
                'division_id' => 1,
                'is_active' => 1,
                'remember_token' => 'jznsnrBykw4NpyabN14uRVGFFXLsjqt3c87ZuwBSzoEehA87RTiZDKRLfX3F',
                'confirmation_code' => str_random(30),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'role_id' => '3',
                'username' => 'student7',
                'body_id' => '1',
                'first_name' => 'student7',
                'last_name' => 'student7',
                'email' => 'student7@gmail.com',
                'gender' => 'M',
                'birth_date' => '2016-01-27 00:00:00',
                'mobile' => '1234567890',
                'password' => bcrypt('123456'),
                'address' => 'maharashtra Pune',
                'alternate_number' => '',
                'avatar' => 'default-user.jpg',
                'parent_id' => '20',
                'roll_number' => '0',
                'emp_type' => 'full_type',
                'division_id' => 1,
                'is_active' => 1,
                'remember_token' => 'jznsnrBykw4NpyabN14uRVGFFXLsjqt3c87ZuwBSzoEehA87RTiZDKRLfX3F',
                'confirmation_code' => str_random(30),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'role_id' => '3',
                'username' => 'student8',
                'body_id' => '1',
                'first_name' => 'student8',
                'last_name' => 'student8',
                'email' => 'student8@gmail.com',
                'gender' => 'M',
                'birth_date' => '2016-01-27 00:00:00',
                'mobile' => '1234567890',
                'password' => bcrypt('123456'),
                'address' => 'maharashtra Pune',
                'alternate_number' => '',
                'avatar' => 'default-user.jpg',
                'parent_id' => '20',
                'roll_number' => '0',
                'emp_type' => 'full_type',
                'division_id' => 1,
                'is_active' => 1,
                'remember_token' => 'jznsnrBykw4NpyabN14uRVGFFXLsjqt3c87ZuwBSzoEehA87RTiZDKRLfX3F',
                'confirmation_code' => str_random(30),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'role_id' => '3',
                'username' => 'student9',
                'body_id' => '1',
                'first_name' => 'student9',
                'last_name' => 'student9',
                'email' => 'student9@gmail.com',
                'gender' => 'M',
                'birth_date' => '2016-01-27 00:00:00',
                'mobile' => '1234567890',
                'password' => bcrypt('123456'),
                'address' => 'maharashtra Pune',
                'alternate_number' => '',
                'avatar' => 'default-user.jpg',
                'parent_id' => '20',
                'roll_number' => '0',
                'emp_type' => 'full_type',
                'division_id' => 1,
                'is_active' => 1,
                'remember_token' => 'jznsnrBykw4NpyabN14uRVGFFXLsjqt3c87ZuwBSzoEehA87RTiZDKRLfX3F',
                'confirmation_code' => str_random(30),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'role_id' => '3',
                'username' => 'student10',
                'body_id' => '1',
                'first_name' => 'student10',
                'last_name' => 'student10',
                'email' => 'student10@gmail.com',
                'gender' => 'M',
                'birth_date' => '2016-01-27 00:00:00',
                'mobile' => '1234567890',
                'password' => bcrypt('123456'),
                'address' => 'maharashtra Pune',
                'alternate_number' => '',
                'avatar' => 'default-user.jpg',
                'parent_id' => '20',
                'roll_number' => '0',
                'emp_type' => 'full_type',
                'division_id' => 1,
                'is_active' => 1,
                'remember_token' => 'jznsnrBykw4NpyabN14uRVGFFXLsjqt3c87ZuwBSzoEehA87RTiZDKRLfX3F',
                'confirmation_code' => str_random(30),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'role_id' => '3',
                'username' => 'student11',
                'body_id' => '1',
                'first_name' => 'student11',
                'last_name' => 'student11',
                'email' => 'student11@gmail.com',
                'gender' => 'M',
                'birth_date' => '2016-01-27 00:00:00',
                'mobile' => '1234567890',
                'password' => bcrypt('123456'),
                'address' => 'maharashtra Pune',
                'alternate_number' => '',
                'avatar' => 'default-user.jpg',
                'parent_id' => '20',
                'roll_number' => '0',
                'emp_type' => 'full_type',
                'division_id' => 2,
                'is_active' => 1,
                'remember_token' => 'jznsnrBykw4NpyabN14uRVGFFXLsjqt3c87ZuwBSzoEehA87RTiZDKRLfX3F',
                'confirmation_code' => str_random(30),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'role_id' => '3',
                'username' => 'student12',
                'body_id' => '1',
                'first_name' => 'student12',
                'last_name' => 'student12',
                'email' => 'student12@gmail.com',
                'gender' => 'M',
                'birth_date' => '2016-01-27 00:00:00',
                'mobile' => '1234567890',
                'password' => bcrypt('123456'),
                'address' => 'maharashtra Pune',
                'alternate_number' => '',
                'avatar' => 'default-user.jpg',
                'parent_id' => '20',
                'roll_number' => '0',
                'emp_type' => 'full_type',
                'division_id' => 2,
                'is_active' => 1,
                'remember_token' => 'jznsnrBykw4NpyabN14uRVGFFXLsjqt3c87ZuwBSzoEehA87RTiZDKRLfX3F',
                'confirmation_code' => str_random(30),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'role_id' => '3',
                'username' => 'student13',
                'body_id' => '1',
                'first_name' => 'student13',
                'last_name' => 'student13',
                'email' => 'student13@gmail.com',
                'gender' => 'M',
                'birth_date' => '2016-01-27 00:00:00',
                'mobile' => '1234567890',
                'password' => bcrypt('123456'),
                'address' => 'maharashtra Pune',
                'alternate_number' => '',
                'avatar' => 'default-user.jpg',
                'parent_id' => '20',
                'roll_number' => '0',
                'emp_type' => 'full_type',
                'division_id' => 2,
                'is_active' => 1,
                'remember_token' => 'jznsnrBykw4NpyabN14uRVGFFXLsjqt3c87ZuwBSzoEehA87RTiZDKRLfX3F',
                'confirmation_code' => str_random(30),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'role_id' => '3',
                'username' => 'student14',
                'body_id' => '1',
                'first_name' => 'student14',
                'last_name' => 'student14',
                'email' => 'student14@gmail.com',
                'gender' => 'M',
                'birth_date' => '2016-01-27 00:00:00',
                'mobile' => '1234567890',
                'password' => bcrypt('123456'),
                'address' => 'maharashtra Pune',
                'alternate_number' => '',
                'avatar' => 'default-user.jpg',
                'parent_id' => '20',
                'roll_number' => '0',
                'emp_type' => 'full_type',
                'division_id' => 2,
                'is_active' => 1,
                'remember_token' => 'jznsnrBykw4NpyabN14uRVGFFXLsjqt3c87ZuwBSzoEehA87RTiZDKRLfX3F',
                'confirmation_code' => str_random(30),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'role_id' => '3',
                'username' => 'student15',
                'body_id' => '1',
                'first_name' => 'student15',
                'last_name' => 'student15',
                'email' => 'student15@gmail.com',
                'gender' => 'M',
                'birth_date' => '2016-01-27 00:00:00',
                'mobile' => '1234567890',
                'password' => bcrypt('123456'),
                'address' => 'maharashtra Pune',
                'alternate_number' => '',
                'avatar' => 'default-user.jpg',
                'parent_id' => '20',
                'roll_number' => '0',
                'emp_type' => 'full_type',
                'division_id' => 2,
                'is_active' => 1,
                'remember_token' => 'jznsnrBykw4NpyabN14uRVGFFXLsjqt3c87ZuwBSzoEehA87RTiZDKRLfX3F',
                'confirmation_code' => str_random(30),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'role_id' => '4',
                'username' => 'parent1',
                'body_id' => '1',
                'first_name' => 'parent1',
                'last_name' => 'parent1',
                'email' => 'parent1@gmail.com',
                'gender' => 'M',
                'birth_date' => '2016-01-27 00:00:00',
                'mobile' => '1234567890',
                'password' => bcrypt('123456'),
                'address' => 'maharashtra Pune',
                'alternate_number' => '',
                'avatar' => 'default-user.jpg',
                'parent_id' => '0',
                'roll_number' => '0',
                'emp_type' => 'full_type',
                'division_id' => 1,
                'is_active' => 1,
                'remember_token' => 'jznsnrBykw4NpyabN14uRVGFFXLsjqt3c87ZuwBSzoEehA87RTiZDKRLfX3F',
                'confirmation_code' => str_random(30),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
        ]);

    }
}
